### ISSUE TITLE
map won't load ... is it because of new google api?

### ISSUE THREAD

**Issue by redknite** [chrisherold/acf-address-map-field#3]
The map on the post edit screen shows up but there is no search button, only location.  If i manually type in the address etc, the data saves, but teh map doesn't show.  If i use the geolocate button to add my own location the map refreshes but doesn't show any new data.  WHen i hit save map goes back to default location.  Any ideas?  on my edit page i'm getting this error:  

"This service requires an API key.  For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key"

**Comment by chrisherold** [comment]
Google requires an api for maps now, I should have add (and will now add) that caveat to the readme. ACF provides a guide to registering an API and adding to your functions.php and then this plugin should work correctly:
https://www.advancedcustomfields.com/blog/google-maps-api-settings/
